spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basic_service
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# 开发环境配置
server:
  # 服务端口
  port: 9001
  tomcat:
    max-http-form-post-size: 256MB
    connection-timeout: 18000



# 持久层配置
mybatis-plus:
  global-config:
    db-config:
      #主键类型
      id-type: ASSIGN_ID
      # 逻辑删除字段
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 表名前缀
  #枚举包扫描
  #  type-enums-package: com.wavenet.common.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

attachment:
  rootPath: C:\dd\
  accessPath: /attachment/**
  api: http://192.168.1.3:9001/attachment/


music:
  tokenKey: admin
  expireMinutes: 300000
  ignoreUrl:
    - /login
    - /doc.html
    - /webjars/**
    - /js/**
    - /css/**
    - /swagger-resources
    - /v2/api-docs
    - /api/pushMessage/**
    - /file/**

